### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by SQReder** [effector/eslint-plugin#40]
Eslint stop with error

```SyntaxError: Failed to load plugin 'effector' declared in '.eslintrc.js': Unexpected token '.'
Referenced from: /home/user/_proj/project/front/.eslintrc.js

/home/user/_proj/project/front/node_modules/eslint-plugin-effector/rules/enforce-store-naming-convention/enforce-store-naming-convention.js:32
            type?.symbol?.escapedName === "Store" &&
                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/_proj/project/front/node_modules/eslint-plugin-effector/index.js:3:40)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

```
    "eslint": "^7.32.0",
    "eslint-plugin-effector": "^0.2.0",
```

**Comment by igorkamyshev** [comment]
Hello! Could you provide your Node.js version, please?

**Comment by SQReder** [comment]
14.17.5

**Comment by igorkamyshev** [comment]
Magic! 🌚

Could you reproduce this case in public repo?
